services:
  mysql:
    image: mysql:8.4
    container_name: net-incident-tracker-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: net_incident_tracker
      MYSQL_USER: net_tracker
      MYSQL_PASSWORD: net_tracker_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot_password",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: