"""add incidents and link reports

Revision ID: 02f346171729
Revises: 857e0a1c564b
Create Date: 2026-06-09 01:06:14.136920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f346171729'
down_revision: Union[str, Sequence[str], None] = '857e0a1c564b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('normalized_address', sa.String(length=255), nullable=False),
    sa.Column('issue_type', sa.Enum('NO_INTERNET', 'LOW_SPEED', 'UNSTABLE_CONNECTION', name='issuetype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='incidentstatus'), nullable=False),
    sa.Column('reports_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_issue_type'), 'incidents', ['issue_type'], unique=False)
    op.create_index(op.f('ix_incidents_normalized_address'), 'incidents', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.add_column('reports', sa.Column('incident_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reports_incident_id'), 'reports', ['incident_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_incident_id'), table_name='reports')
    op.drop_column('reports', 'incident_id')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_normalized_address'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_issue_type'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
