"""create reports table

Revision ID: 857e0a1c564b
Revises: 
Create Date: 2026-06-09 00:35:52.339249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857e0a1c564b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('issue_type', sa.Enum('NO_INTERNET', 'LOW_SPEED', 'UNSTABLE_CONNECTION', name='issuetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_address'), 'reports', ['address'], unique=False)
    op.create_index(op.f('ix_reports_issue_type'), 'reports', ['issue_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_issue_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_address'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
